language: php

dist: bionic

os: linux

git:
  depth: false

php:
  - 7.4

stages:
  - test
  - name: build
    if: tag IS present

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - PLATFORMS=linux/amd64,linux/arm/v7,linux/arm64

jobs:
  include:
    - stage: test
      language: php
      before_script:
        - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction --prefer-dist
      script:
        - vendor/bin/phpunit --testdox --coverage-clover tests_coverage.xml --log-junit tests_log.xml
    - stage: build
      language: shell
      before_install:
        - curl -sf https://test.docker.com | sh
        - docker --version
      install:
        - echo $DOCKER_PASSWORD | docker login --username jorijn --password-stdin &> /dev/null
        - touch ${TRAVIS_BUILD_DIR}/version.json
        - |
          cat > "${TRAVIS_BUILD_DIR}/version.json" <<FILE
          {
            "built_from_branch": "${TRAVIS_BRANCH}",
            "commit_id": "${TRAVIS_COMMIT}",
            "build_date": "$(date)",
            "version": "${TRAVIS_TAG}",
            "build_number": "${TRAVIS_BUILD_NUMBER}"
          }
        - docker run --privileged linuxkit/binfmt:v0.8
        - docker buildx create --use
        - docker buildx build --progress plain --platform "$PLATFORMS" -t jorijn/bitcoin-dca:latest -t jorijn/bitcoin-dca:$TRAVIS_TAG --push .
