parameters:
  dca.application_title: 'BL3P Bitcoin DCA Tool'
  env(BL3P_API_URL): ''
  env(BL3P_PUBLIC_KEY): ''
  env(BL3P_PRIVATE_KEY): ''
  env(BL3P_WITHDRAW_ADDRESS): ''
  env(BL3P_WITHDRAW_XPUB): ~

services:
  dca.command.buy:
    class: Jorijn\Bl3pDca\Command\BuyCommand
    arguments:
      - 'buy'
      - '@dca.api.client'
      - '@dca.repository.tag_integer.balance'
    tags:
      - bl3p-dca.cli

  dca.command.withdraw:
    class: Jorijn\Bl3pDca\Command\WithdrawCommand
    arguments:
      - 'withdraw'
      - '@dca.api.client'
      - !tagged_iterator bl3p-dca.address_provider
      - '@dca.repository.tag_integer.balance'
    tags:
      - bl3p-dca.cli

  dca.command.balance:
    class: Jorijn\Bl3pDca\Command\BalanceCommand
    arguments:
      - 'balance'
      - '@dca.api.client'
    tags:
      - bl3p-dca.cli

  dca.command.verify_xpub:
    class: Jorijn\Bl3pDca\Command\VerifyXPubCommand
    arguments:
      - 'verify-xpub'
      - '@dca.factory.derive_from_master_public_key'
      - '%env(BL3P_WITHDRAW_XPUB)%'
      - 'BL3P_WITHDRAW_XPUB'
    tags:
      - bl3p-dca.cli

  dca.factory.api_client:
    class: Jorijn\Bl3pDca\Factory\Bl3pClientFactory
    arguments:
      - '%env(string:BL3P_API_URL)%'
      - '%env(string:BL3P_PUBLIC_KEY)%'
      - '%env(string:BL3P_PRIVATE_KEY)%'

  dca.factory.derive_from_master_public_key:
    class: Jorijn\Bl3pDca\Factory\AddressFromMasterPublicKeyFactory

  dca.api.client:
    class: Jorijn\Bl3pDca\Client\Bl3pClient
    factory:
      - '@dca.factory.api_client'
      - 'createApi'

  # this is the default address provider, new ones with special capabilities can be configured with more priority
  dca.address_provider.simple:
    class: Jorijn\Bl3pDca\Provider\SimpleWithdrawAddressProvider
    arguments:
      - '@dca.validator.bitcoin_address'
      - '%env(string:BL3P_WITHDRAW_ADDRESS)%'
    tags:
      - { name: 'bl3p-dca.address_provider', priority: -1000 }

  # this address provider parses the configured xpub and returns a fresh address for each transaction
  # DISABLED FOR NOW, WORK IN PROGRESS
  dca.address_provider.xpub:
    class: Jorijn\Bl3pDca\Provider\XpubWithdrawAddressProvider
    arguments:
      - '@dca.validator.bitcoin_address'
      - '@dca.factory.derive_from_master_public_key'
      - '%env(BL3P_WITHDRAW_XPUB)%'
  #    tags:
  #      - { name: 'bl3p-dca.address_provider', priority: -500 }

  dca.validator.bitcoin_address:
    class: Jorijn\Bl3pDca\Validator\BitcoinAddressValidator
    arguments:
      - '@dca.bitwasp.address.creator'

  dca.application:
    class: Symfony\Component\Console\Application
    public: true
    arguments:
      - '%dca.application_title%'

  dca.repository.tag_integer.balance:
    class: Jorijn\Bl3pDca\Repository\JsonFileTaggedIntegerRepository
    arguments:
      - '%dca.application.path%/var/storage/balance.db'

  dca.repository.tag_integer.xpub_index:
    class: Jorijn\Bl3pDca\Repository\JsonFileTaggedIntegerRepository
    arguments:
      - '%dca.application.path%/var/storage/xpub_index.db'

  dca.bitwasp.address.creator:
    class: BitWasp\Bitcoin\Address\AddressCreator
