parameters:
  application_title: 'BL3P Bitcoin DCA Tool'
  env(BL3P_API_URL): ''
  env(BL3P_PUBLIC_KEY): ''
  env(BL3P_PRIVATE_KEY): ''
  env(BL3P_WITHDRAW_ADDRESS): ''
  env(BL3P_WITHDRAW_XPUB): ~

services:
  ######################################################################
  # CLI Commands
  ######################################################################
  command.buy:
    class: Jorijn\Bl3pDca\Command\BuyCommand
    arguments:
      - '@api.client'
      - '@repository.tag_integer.balance'
      - '@logger'
    tags:
      - { name: console.command, command: 'buy' }

  command.withdraw:
    class: Jorijn\Bl3pDca\Command\WithdrawCommand
    arguments:
      - '@api.client'
      - !tagged_iterator bl3p-address_provider
      - '@repository.tag_integer.balance'
      - '@event_dispatcher'
    tags:
      - { name: console.command, command: 'withdraw' }

  command.balance:
    class: Jorijn\Bl3pDca\Command\BalanceCommand
    arguments:
      - '@api.client'
    tags:
      - { name: console.command, command: 'balance' }

  command.verify_xpub:
    class: Jorijn\Bl3pDca\Command\VerifyXPubCommand
    arguments:
      - '@factory.derive_from_master_public_key'
      - '@repository.tag_integer.xpub_index'
      - '%env(BL3P_WITHDRAW_XPUB)%'
      - 'BL3P_WITHDRAW_XPUB'
    tags:
      - { name: console.command, command: 'verify-xpub' }

  ######################################################################
  # Factories
  ######################################################################
  factory.api_client:
    class: Jorijn\Bl3pDca\Factory\Bl3pClientFactory
    arguments:
      - '%env(string:BL3P_API_URL)%'
      - '%env(string:BL3P_PUBLIC_KEY)%'
      - '%env(string:BL3P_PRIVATE_KEY)%'
      - '@logger'

  factory.derive_from_master_public_key:
    class: Jorijn\Bl3pDca\Factory\AddressFromMasterPublicKeyFactory

  ######################################################################
  # API Clients
  ######################################################################
  api.client:
    class: Jorijn\Bl3pDca\Client\Bl3pClient
    factory:
      - '@factory.api_client'
      - 'createApi'

  ######################################################################
  # Address Providers
  ######################################################################
  address_provider.simple:
    class: Jorijn\Bl3pDca\Provider\SimpleWithdrawAddressProvider
    arguments:
      - '@validator.bitcoin_address'
      - '%env(string:BL3P_WITHDRAW_ADDRESS)%'
    tags:
      - { name: 'bl3p-address_provider', priority: -1000 }

  address_provider.xpub:
    class: Jorijn\Bl3pDca\Provider\XpubWithdrawAddressProvider
    arguments:
      - '@validator.bitcoin_address'
      - '@factory.derive_from_master_public_key'
      - '@repository.tag_integer.xpub_index'
      - '%env(BL3P_WITHDRAW_XPUB)%'
    tags:
      - { name: bl3p-address_provider, priority: -500 }

  ######################################################################
  # Validators
  ######################################################################
  validator.bitcoin_address:
    class: Jorijn\Bl3pDca\Validator\BitcoinAddressValidator
    arguments:
      - '@bitwasp.address.creator'

  ######################################################################
  # The CLI application
  ######################################################################
  application:
    class: Symfony\Component\Console\Application
    public: true
    arguments:
      - '%application_title%'

  ######################################################################
  # Repositories
  ######################################################################
  repository.tag_integer.balance:
    class: Jorijn\Bl3pDca\Repository\JsonFileTaggedIntegerRepository
    arguments:
      - '%application.path%/var/storage/balance.db'

  repository.tag_integer.xpub_index:
    class: Jorijn\Bl3pDca\Repository\JsonFileTaggedIntegerRepository
    arguments:
      - '%application.path%/var/storage/xpub_index.db'

  ######################################################################
  # Event Listeners
  ######################################################################
  event_listener.xpub_address_used:
    class: Jorijn\Bl3pDca\EventListener\XPubAddressUsedListener
    arguments:
      - '@repository.tag_integer.xpub_index'
      - '@factory.derive_from_master_public_key'
      - '@logger'
      - '%env(BL3P_WITHDRAW_XPUB)%'
    tags:
      - { name: kernel.event_listener, event: Jorijn\Bl3pDca\Event\WithdrawSuccessEvent, method: onWithdrawAddressUsed }

  ######################################################################
  # Third Party Components
  ######################################################################
  bitwasp.address.creator:
    class: BitWasp\Bitcoin\Address\AddressCreator

  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher
    public: true

  logger.stream_handler:
    class: Monolog\Handler\StreamHandler
    arguments:
      - '%application.path%/var/logs/bl3p-dca.log'

  logger:
    class: Monolog\Logger
    arguments:
      - 'bl3p-dca'
      - ['@logger.stream_handler']
