parameters:
  application_title: 'Bitcoin DCA Tool'
  application_version: 'DEVELOPMENT'
  buy_fill_timeout: 30
  version_updates.hostname: 'https://api.github.com'
  version_updates.path: '/repos/jorijn/bitcoin-dca/releases/latest'

  # BL3P settings
  env(BL3P_API_URL): 'https://api.bl3p.eu/1/'
  env(BL3P_PUBLIC_KEY): ''
  env(BL3P_PRIVATE_KEY): ''
  env(BL3P_WITHDRAW_ADDRESS): ''
  env(BL3P_WITHDRAW_XPUB): ~

  # bitvavo settings
  env(BITVAVO_API_URL): 'https://api.bitvavo.com/v2/'
  env(BITVAVO_API_KEY): ~
  env(BITVAVO_API_SECRET): ~

  # kraken settings
  env(KRAKEN_API_URL): 'https://api.kraken.com/'
  env(KRAKEN_API_KEY): ~
  env(KRAKEN_PRIVATE_KEY): ~
  env(KRAKEN_WITHDRAW_DESCRIPTION): ~
  env(KRAKEN_FEE_STRATEGY): 'include'
  env(KRAKEN_TRADING_AGREEMENT): ~

  # binance settings
  env(BINANCE_API_URL): 'https://api.binance.com/'
  env(BINANCE_API_KEY): ~
  env(BINANCE_API_SECRET): ~

  # generic application settings
  env(WITHDRAW_ADDRESS): '%env(BL3P_WITHDRAW_ADDRESS)%'
  env(WITHDRAW_XPUB): '%env(BL3P_WITHDRAW_XPUB)%'
  env(EXCHANGE): 'bl3p'
  env(BASE_CURRENCY): 'EUR'
  env(DEBUG): 'false'
  env(DISABLE_VERSION_CHECK): 'false'

  # xpub fallback settings
  env(XPUB_PYTHON_CLI): '/usr/bin/python3 /app/resources/xpub_derive/main.py'

services:
  ######################################################################
  # CLI Commands
  ######################################################################
  command.buy:
    class: Jorijn\Bitcoin\Dca\Command\BuyCommand
    arguments:
      - '@service.buy'
      - '@serializer'
      - '%env(BASE_CURRENCY)%'
    tags:
      - { name: console.command, command: 'buy' }

  command.withdraw:
    class: Jorijn\Bitcoin\Dca\Command\WithdrawCommand
    arguments:
      - '@service.withdraw'
    tags:
      - { name: console.command, command: 'withdraw' }

  command.balance:
    class: Jorijn\Bitcoin\Dca\Command\BalanceCommand
    arguments:
      - '@service.balance'
    tags:
      - { name: console.command, command: 'balance' }

  command.verify_xpub:
    class: Jorijn\Bitcoin\Dca\Command\VerifyXPubCommand
    arguments:
      - '@component.derive_from_master_public_key'
      - '@repository.tag_integer.xpub_index'
      - '%env(WITHDRAW_XPUB)%'
      - 'WITHDRAW_XPUB'
    tags:
      - { name: console.command, command: 'verify-xpub' }

  command.version:
    class: Jorijn\Bitcoin\Dca\Command\VersionCommand
    arguments:
      - '%application.path%/version.json'
    tags:
      - { name: console.command, command: 'version' }

  ######################################################################
  # Factories
  ######################################################################
  factory.derive_from_master_public_key.component:
    class: Jorijn\Bitcoin\Dca\Factory\DeriveFromMasterPublicKeyComponentFactory
    arguments:
      - !tagged_iterator derive-from-master-public-key

  ######################################################################
  # Components
  ######################################################################
  component.derive_from_master_public_key:
    class: Jorijn\Bitcoin\Dca\Component\AddressFromMasterPublicKeyComponentInterface
    factory: ['@factory.derive_from_master_public_key.component', 'createDerivationComponent']

  component.derive_from_master_public_key_bitwasp:
    class: Jorijn\Bitcoin\Dca\Component\AddressFromMasterPublicKeyComponent
    tags:
      - { name: derive-from-master-public-key, priority: -500 }

  component.derive_from_master_public_key_external:
    class: Jorijn\Bitcoin\Dca\Component\ExternalAddressFromMasterPublicKeyComponent
    arguments:
      - '@logger'
      - '%env(XPUB_PYTHON_CLI)%'
    tags:
      - { name: derive-from-master-public-key, priority: -1000 }

  ######################################################################
  # API Clients
  ######################################################################
  api.client.bl3p:
    class: Jorijn\Bitcoin\Dca\Client\Bl3pClient
    arguments:
      - '@http_client.bl3p'
      - '@logger'
      - '%env(string:BL3P_PUBLIC_KEY)%'
      - '%env(string:BL3P_PRIVATE_KEY)%'

  http_client.bl3p:
    class: Symfony\Contracts\HttpClient\HttpClientInterface
    factory:
      - Symfony\Component\HttpClient\HttpClient
      - create
    arguments:
      - base_uri: '%env(string:BL3P_API_URL)%'

  http_client.bl3p.verbose:
    class: Jorijn\Bitcoin\Dca\Client\VerboseHttpClientDecorator
    decorates: http_client.bitvavo
    arguments: [ '@.inner', '@logger', '%env(bool:DEBUG)%' ]

  api.client.bitvavo:
    class: Jorijn\Bitcoin\Dca\Client\BitvavoClient
    arguments:
      - '@http_client.bitvavo'
      - '@logger'
      - '%env(string:BITVAVO_API_KEY)%'
      - '%env(string:BITVAVO_API_SECRET)%'

  http_client.bitvavo:
    class: Symfony\Contracts\HttpClient\HttpClientInterface
    factory:
      - Symfony\Component\HttpClient\HttpClient
      - create
    arguments:
      - base_uri: '%env(string:BITVAVO_API_URL)%'

  http_client.bitvavo.verbose:
    class: Jorijn\Bitcoin\Dca\Client\VerboseHttpClientDecorator
    decorates: http_client.bitvavo
    arguments: [ '@.inner', '@logger', '%env(bool:DEBUG)%' ]

  api.client.kraken:
    class: Jorijn\Bitcoin\Dca\Client\KrakenClient
    arguments:
      - '@http_client.kraken'
      - '@logger'
      - '%env(string:KRAKEN_API_KEY)%'
      - '%env(string:KRAKEN_PRIVATE_KEY)%'

  http_client.kraken:
    class: Symfony\Contracts\HttpClient\HttpClientInterface
    factory:
      - Symfony\Component\HttpClient\HttpClient
      - create
    arguments:
      - base_uri: '%env(string:KRAKEN_API_URL)%'

  http_client.kraken.verbose:
    class: Jorijn\Bitcoin\Dca\Client\VerboseHttpClientDecorator
    decorates: http_client.kraken
    arguments: [ '@.inner', '@logger', '%env(bool:DEBUG)%' ]

  api.client.binance:
    class: Jorijn\Bitcoin\Dca\Client\BinanceClient
    arguments:
      - '@http_client.binance'
      - '%env(string:BINANCE_API_KEY)%'
      - '%env(string:BINANCE_API_SECRET)%'

  http_client.binance:
    class: Symfony\Contracts\HttpClient\HttpClientInterface
    factory:
      - Symfony\Component\HttpClient\HttpClient
      - create
    arguments:
      - base_uri: '%env(string:BINANCE_API_URL)%'

  http_client.binance.verbose:
    class: Jorijn\Bitcoin\Dca\Client\VerboseHttpClientDecorator
    decorates: http_client.binance
    arguments: [ '@.inner', '@logger', '%env(bool:DEBUG)%' ]

  http_client.version_updates:
    class: Symfony\Contracts\HttpClient\HttpClientInterface
    factory:
      - Symfony\Component\HttpClient\HttpClient
      - create
    arguments:
      - base_uri: '%version_updates.hostname%'

  ######################################################################
  # Address Providers
  ######################################################################
  address_provider.simple:
    class: Jorijn\Bitcoin\Dca\Provider\SimpleWithdrawAddressProvider
    arguments:
      - '@validator.bitcoin_address'
      - '%env(string:WITHDRAW_ADDRESS)%'
    tags:
      - { name: 'withdraw-address-provider', priority: -1000 }

  address_provider.xpub:
    class: Jorijn\Bitcoin\Dca\Provider\XpubWithdrawAddressProvider
    arguments:
      - '@validator.bitcoin_address'
      - '@component.derive_from_master_public_key'
      - '@repository.tag_integer.xpub_index'
      - '%env(WITHDRAW_XPUB)%'
    tags:
      - { name: withdraw-address-provider, priority: -500 }

  ######################################################################
  # Validators
  ######################################################################
  validator.bitcoin_address:
    class: Jorijn\Bitcoin\Dca\Validator\BitcoinAddressValidator
    arguments:
      - '@bitwasp.address.creator'

  ######################################################################
  # The CLI application
  ######################################################################
  application:
    class: Symfony\Component\Console\Application
    public: true
    arguments:
      - '%application_title%'
      - '%application_version%'

  ######################################################################
  # Repositories
  ######################################################################
  repository.tag_integer.balance:
    class: Jorijn\Bitcoin\Dca\Repository\JsonFileTaggedIntegerRepository
    arguments:
      - '%application.path%/var/storage/balance.db'

  repository.tag_integer.xpub_index:
    class: Jorijn\Bitcoin\Dca\Repository\JsonFileTaggedIntegerRepository
    arguments:
      - '%application.path%/var/storage/xpub_index.db'

  ######################################################################
  # Event Listeners
  ######################################################################
  event_listener.xpub_address_used:
    class: Jorijn\Bitcoin\Dca\EventListener\XPubAddressUsedListener
    arguments:
      - '@repository.tag_integer.xpub_index'
      - '@component.derive_from_master_public_key'
      - '@logger'
      - '%env(WITHDRAW_XPUB)%'
    tags:
      - { name: kernel.event_listener, event: Jorijn\Bitcoin\Dca\Event\WithdrawSuccessEvent, method: onWithdrawAddressUsed }

  event_listener.increase_tagged_balance:
    class: Jorijn\Bitcoin\Dca\EventListener\IncreaseTaggedBalanceListener
    arguments:
      - '@repository.tag_integer.balance'
      - '@logger'
    tags:
      - { name: kernel.event_listener, event: Jorijn\Bitcoin\Dca\Event\BuySuccessEvent, method: onBalanceIncrease }

  event_listener.reset_tagged_balance:
    class: Jorijn\Bitcoin\Dca\EventListener\ResetTaggedBalanceListener
    arguments:
      - '@repository.tag_integer.balance'
      - '@logger'
    tags:
      - { name: kernel.event_listener, event: Jorijn\Bitcoin\Dca\Event\WithdrawSuccessEvent, method: onWithdrawSucces }

  event_listener.check_for_updates:
    class: Jorijn\Bitcoin\Dca\EventListener\CheckForUpdatesListener
    arguments:
      - '@http_client.version_updates'
      - '%application_version%'
      - '%version_updates.path%'
      - '%env(bool:DISABLE_VERSION_CHECK)%'
    tags:
      - { name: kernel.event_listener, event: console.terminate, method: onConsoleTerminated }

  ######################################################################
  # Services
  ######################################################################
  service.buy:
    class: Jorijn\Bitcoin\Dca\Service\BuyService
    arguments:
      - '@event_dispatcher'
      - '@logger'
      - '%env(EXCHANGE)%'
      - !tagged_iterator exchange-buy-service
      - '%buy_fill_timeout%'

  service.withdraw:
    class: Jorijn\Bitcoin\Dca\Service\WithdrawService
    arguments:
      - !tagged_iterator withdraw-address-provider
      - !tagged_iterator exchange-withdraw-service
      - '@repository.tag_integer.balance'
      - '@event_dispatcher'
      - '@logger'
      - '%env(EXCHANGE)%'

  service.balance:
    class: Jorijn\Bitcoin\Dca\Service\BalanceService
    arguments:
      - !tagged_iterator exchange-balance-service
      - '%env(EXCHANGE)%'

  ##
  ## BL3P
  ##
  service.buy.bl3p:
    class: Jorijn\Bitcoin\Dca\Service\Bl3p\Bl3pBuyService
    arguments:
      - '@api.client.bl3p'
      - '%env(BASE_CURRENCY)%'
    tags:
      - { name: exchange-buy-service }

  service.withdraw.bl3p:
    class: Jorijn\Bitcoin\Dca\Service\Bl3p\Bl3pWithdrawService
    arguments:
      - '@api.client.bl3p'
      - '@logger'
    tags:
      - { name: exchange-withdraw-service }

  service.balance.bl3p:
    class: Jorijn\Bitcoin\Dca\Service\Bl3p\Bl3pBalanceService
    arguments:
      - '@api.client.bl3p'
    tags:
      - { name: exchange-balance-service }

  ##
  ## Bitvavo
  ##
  service.buy.bitvavo:
    class: Jorijn\Bitcoin\Dca\Service\Bitvavo\BitvavoBuyService
    arguments:
      - '@api.client.bitvavo'
      - '%env(BASE_CURRENCY)%'
    tags:
      - { name: exchange-buy-service }

  service.withdraw.bitvavo:
    class: Jorijn\Bitcoin\Dca\Service\Bitvavo\BitvavoWithdrawService
    arguments:
      - '@api.client.bitvavo'
      - '@logger'
    tags:
      - { name: exchange-withdraw-service }

  service.balance.bitvavo:
    class: Jorijn\Bitcoin\Dca\Service\Bitvavo\BitvavoBalanceService
    arguments:
      - '@api.client.bitvavo'
    tags:
      - { name: exchange-balance-service }

  ##
  ## Kraken
  ##
  service.buy.kraken:
    class: Jorijn\Bitcoin\Dca\Service\Kraken\KrakenBuyService
    arguments:
      - '@api.client.kraken'
      - '%env(BASE_CURRENCY)%'
      - '%env(KRAKEN_FEE_STRATEGY)%'
      - '%env(KRAKEN_TRADING_AGREEMENT)%'
    tags:
      - { name: exchange-buy-service }

  service.withdraw.kraken:
    class: Jorijn\Bitcoin\Dca\Service\Kraken\KrakenWithdrawService
    arguments:
      - '@api.client.kraken'
      - '@logger'
      - '%env(KRAKEN_WITHDRAW_DESCRIPTION)%'
    tags:
      - { name: exchange-withdraw-service }

  service.balance.kraken:
    class: Jorijn\Bitcoin\Dca\Service\Kraken\KrakenBalanceService
    arguments:
      - '@api.client.kraken'
    tags:
      - { name: exchange-balance-service }

  ##
  ## Binance
  ##
  service.buy.binance:
    class: Jorijn\Bitcoin\Dca\Service\Binance\BinanceBuyService
    arguments:
      - '@api.client.binance'
      - '%env(BASE_CURRENCY)%'
    tags:
      - { name: exchange-buy-service }

  service.withdraw.binance:
    class: Jorijn\Bitcoin\Dca\Service\Binance\BinanceWithdrawService
    arguments:
      - '@api.client.binance'
    tags:
      - { name: exchange-withdraw-service }

  service.balance.binance:
    class: Jorijn\Bitcoin\Dca\Service\Binance\BinanceBalanceService
    arguments:
      - '@api.client.binance'
    tags:
      - { name: exchange-balance-service }

  ######################################################################
  # Third Party Components
  ######################################################################
  bitwasp.address.creator:
    class: BitWasp\Bitcoin\Address\AddressCreator

  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher
    public: true

  logger.stream_handler:
    class: Monolog\Handler\StreamHandler
    arguments:
      - '%application.path%/var/logs/bitcoin-dca.log'

  logger:
    class: Monolog\Logger
    arguments:
      - 'bitcoin-dca'
      - ['@logger.stream_handler']

  serializer:
    class: Symfony\Component\Serializer\Serializer
    public: true
    arguments:
      - []
      - []

  serializer.encoder.json:
    class: Symfony\Component\Serializer\Encoder\JsonEncoder
    tags:
      - serializer.encoder

  serializer.encoder.xml:
    class: Symfony\Component\Serializer\Encoder\XmlEncoder
    tags:
      - serializer.encoder

  serializer.encoder.csv:
    class: Symfony\Component\Serializer\Encoder\CsvEncoder
    tags:
      - serializer.encoder

  serializer.encoder.yaml:
    class: Symfony\Component\Serializer\Encoder\YamlEncoder
    tags:
      - serializer.encoder

  serializer.normalizer.object:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    tags:
      - serializer.normalizer
