name: Test and build bitcoin-dca

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ######################
  # Composer
  ######################

  composer:
    
    runs-on: ubuntu-latest
    container:
      image: composer:latest
    
    steps:
    - uses: actions/checkout@v2 
    - name: Composer install
      run: composer help
        
  ######################
  # PHPunit
  ######################
  
  phpunit:
    
    needs: composer

    runs-on: ubuntu-latest
    container:
      image: phpunit/phpunit
    
    steps:
    - uses: actions/checkout@v2 
    - name: PHPunit
      run: |
        ...
  
  ######################
  # Build Docker image
  ######################

  build-and-push-docker-image:
    
    needs: phpunit
    
    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker image
      run: |
        echo $DOCKER_PASSWORD | docker login --username jorijn --password-stdin &> /dev/null
        docker run --privileged linuxkit/binfmt:v0.8
        docker buildx create --use
        docker buildx build --progress plain --platform "$PLATFORMS" -t jorijn/bitcoin-dca:latest --push .
      env:
        PLATFORMS=linux/amd64,linux/arm/v7,linux/arm64
