name: Run the Bitcoin-DCA automated tests every time some code changes

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image and execute the testsuite
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          target: testing_stage
          load: true
          tags: jorijn/bitcoin-dca:ci
          cache-from: type=registry,ref=jorijn/bitcoin-dca:latest

      - name: Extract the test logging artifacts from the container that was built
        if: success() || failure()
        run: |
          docker run --rm --entrypoint= -v ${GITHUB_WORKSPACE}:/app/ jorijn/bitcoin-dca:ci sh -c "cp /tmp/tests_*.xml /app/"
          sed -i "s/\/app\//\/github\/workspace\//g" tests_coverage.xml tests_log.xml

      - name: Upload logging artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test_coverage_and_logging
          path: |
            tests_coverage.xml
            tests_log.xml
            
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: 'tests_*.xml'

  sonarcloud:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test_coverage_and_logging
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
