name: Run the Bitcoin-DCA automated tests every time some code changes

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker development image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: development_build
          load: true
          tags: jorijn/bitcoin-dca:ci
          cache-from: type=registry,ref=jorijn/bitcoin-dca:latest

      - name: Run the PHPUnit tests
        run: docker run --rm --entrypoint= -v ${GITHUB_WORKSPACE}:/app/ jorijn/bitcoin-dca:ci vendor/bin/phpunit --testdox --coverage-clover /tmp/tests_coverage.xml --log-junit /tmp/tests_log.xml

      - name: Run the Behat integration tests
        run: docker run --rm --entrypoint= -v ${GITHUB_WORKSPACE}:/app/ jorijn/bitcoin-dca:ci vendor/bin/behat -f pretty

      - name: Extract the test logging artifacts generated from the PHPUnit tests
        run: |
          docker run --rm --entrypoint= -v ${GITHUB_WORKSPACE}:/app/ jorijn/bitcoin-dca:ci sh -c "cp /tmp/tests_*.xml /app/"
          sed -i "s/\/app\//\/github\/workspace\//g" tests_coverage.xml tests_log.xml

      - name: Upload logging artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test_coverage_and_logging
          path: |
            tests_coverage.xml
            tests_log.xml

  sonarcloud:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: test_coverage_and_logging
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
